### ISSUE TITLE
Administrator > Namespce >  secret이 목록에 표시되지 않음.

### ISSUE THREAD

**Issue by lay126** [cnpst/zcp-portal-ui#51]
Administrator > Namespace에서 secret이 목록에 표시되지 않음. (default Namespace한정)
다른 Namespace에서 생성된 secret들은 잘 표시되고 있음. 

대상 클러스터 : cloudzcp-fsk-prd

**Comment by yanghoon** [comment]
Secret 의 meta.annotations 처리 중, NPE 발생
```java
2019-05-23 07:58:09.094  INFO 1 --- [io-8181-exec-10] c.s.c.z.a.i.service.impl.IamRestClient   : ===> Request Url : http://zcp-iam:80/iam/namespace/default/secrets
2019-05-23 07:58:09.190  INFO 1 --- [io-8181-exec-10] c.s.c.z.a.i.service.impl.IamRestClient   : ===> Response status : 200
2019-05-23 07:58:09.190  INFO 1 --- [io-8181-exec-10] c.s.c.z.a.i.service.impl.IamRestClient   : ===> Response body msg : Success
2019-05-23 07:58:09.190  INFO 1 --- [io-8181-exec-10] c.s.c.z.a.i.service.impl.IamRestClient   : ===> Response body code : 200
2019-05-23 07:58:09.191  INFO 1 --- [io-8181-exec-10] c.s.c.z.a.i.service.impl.IamRestClient   : ===> Response body data : {apiVersion=v1, items=[{apiVersion=null, data={.dockerconfigjson=eyJhdXRocyI6eyJyZWdpc3RyeS5hdS1zeWQuYmx1ZW1peC5uZXQiOnsidXNlcm5hbWUiOiJ0b2tlbiIsInBhc3N3b3JkIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnFkR2tpT2lJMk5USmpZalF6T0MxaFpEQXdMVFUxTlRNdE9HVTRPQzA1WWpnME9HSXlZbVZqTlRFaUxDSnBjM01pT2lKeVpXZHBjM1J5ZVM1aGRTMXplV1F1WW14MVpXMXBlQzV1WlhRaWZRLlByOVhaNURUbTV6UV8xTnE1TkR2ZDlwVVZ6SkNzQVMwNWpvekpXTlo2MVEiLCJlbWFpbCI6InRva2VuIiwiYXV0aCI6ImRHOXJaVzQ2WlhsS2FHSkhZMmxQYVVwSlZYcEpNVTVwU1hOSmJsSTFZME5KTmtscmNGaFdRMG81TG1WNVNuRmtSMnRwVDJsSk1rNVVTbXBaYWxGNlQwTXhhRnBFUVhkTVZGVXhUbFJOZEU5SFZUUlBRekExV1dwbk1FOUhTWGxaYlZacVRsUkZhVXhEU25Cak0wMXBUMmxLZVZwWFpIQmpNMUo1WlZNMWFHUlRNWHBsVjFGMVdXMTRNVnBYTVhCbFF6VjFXbGhSYVdaUkxsQnlPVmhhTlVSVWJUVjZVVjh4VG5FMVRrUjJaRGx3VlZaNlNrTnpRVk13TldwdmVrcFhUbG8yTVZFPSJ9fX0=}, kind=null, metadata={annotations=null, clusterName=null, creationTimestamp=1549974947000, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=null, generateName=null, generation=null, initializers=null, labels=null, name=bluemix-default-secret, namespace=default, ownerReferences=null, resourceVersion=349, selfLink=/api/v1/namespaces/default/secrets/bluemix-default-secret, uid=b900b387-2ec2-11e9-b349-8205fcc0103a}, stringData=null, type=kubernetes.io/dockerconfigjson}, {apiVersion=null, data={.dockerconfigjson=eyJhdXRocyI6eyJyZWdpc3RyeS5ibHVlbWl4Lm5ldCI6eyJ1c2VybmFtZSI6InRva2VuIiwicGFzc3dvcmQiOiJleUpoYkdjaU9pSklVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKcWRHa2lPaUl5Wm1NeU9USTFOaTFrWmpkbUxUVXhaVE10WVRrNVpTMDFNbVF4TURCbE5qTmlOMklpTENKcGMzTWlPaUp5WldkcGMzUnllUzVpYkhWbGJXbDRMbTVsZENKOS5DLVVud1A2ZkdzRkpYemh4WHQ1a3NFTkZDdHg5UnJjUDZ4enBscXZBRXY0IiwiZW1haWwiOiJ0b2tlbiIsImF1dGgiOiJkRzlyWlc0NlpYbEthR0pIWTJsUGFVcEpWWHBKTVU1cFNYTkpibEkxWTBOSk5rbHJjRmhXUTBvNUxtVjVTbkZrUjJ0cFQybEplVnB0VFhsUFZFa3hUbWt4YTFwcVpHMU1WRlY0V2xSTmRGbFVhelZhVXpBeFRXMVJlRTFFUW14T2FrNXBUakpKYVV4RFNuQmpNMDFwVDJsS2VWcFhaSEJqTTFKNVpWTTFhV0pJVm14aVYydzBURzAxYkdSRFNqa3VReTFWYm5kUU5tWkhjMFpLV0hwb2VGaDBOV3R6UlU1R1EzUjRPVkp5WTFBMmVIcHdiSEYyUVVWMk5BPT0ifX19}, kind=null, metadata={annotations=null, clusterName=null, creationTimestamp=1549974959000, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=null, generateName=null, generation=null, initializers=null, labels=null, name=bluemix-default-secret-international, namespace=default, ownerReferences=null, resourceVersion=372, selfLink=/api/v1/namespaces/default/secrets/bluemix-default-secret-international, uid=c0644e48-2ec2-11e9-b3ca-82c44f299505}, stringData=null, type=kubernetes.io/dockerconfigjson}, {apiVersion=null, data={.dockerconfigjson=eyJhdXRocyI6eyJyZWdpc3RyeS5hdS1zeWQuYmx1ZW1peC5uZXQiOnsidXNlcm5hbWUiOiJ0b2tlbiIsInBhc3N3b3JkIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnFkR2tpT2lJMk5USmpZalF6T0MxaFpEQXdMVFUxTlRNdE9HVTRPQzA1WWpnME9HSXlZbVZqTlRFaUxDSnBjM01pT2lKeVpXZHBjM1J5ZVM1aGRTMXplV1F1WW14MVpXMXBlQzV1WlhRaWZRLlByOVhaNURUbTV6UV8xTnE1TkR2ZDlwVVZ6SkNzQVMwNWpvekpXTlo2MVEiLCJlbWFpbCI6InRva2VuIiwiYXV0aCI6ImRHOXJaVzQ2WlhsS2FHSkhZMmxQYVVwSlZYcEpNVTVwU1hOSmJsSTFZME5KTmtscmNGaFdRMG81TG1WNVNuRmtSMnRwVDJsSk1rNVVTbXBaYWxGNlQwTXhhRnBFUVhkTVZGVXhUbFJOZEU5SFZUUlBRekExV1dwbk1FOUhTWGxaYlZacVRsUkZhVXhEU25Cak0wMXBUMmxLZVZwWFpIQmpNMUo1WlZNMWFHUlRNWHBsVjFGMVdXMTRNVnBYTVhCbFF6VjFXbGhSYVdaUkxsQnlPVmhhTlVSVWJUVjZVVjh4VG5FMVRrUjJaRGx3VlZaNlNrTnpRVk13TldwdmVrcFhUbG8yTVZFPSJ9fX0=}, kind=null, metadata={annotations=null, clusterName=null, creationTimestamp=1549974953000, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=null, generateName=null, generation=null, initializers=null, labels=null, name=bluemix-default-secret-regional, namespace=default, ownerReferences=null, resourceVersion=361, selfLink=/api/v1/namespaces/default/secrets/bluemix-default-secret-regional, uid=bc6ca885-2ec2-11e9-b3ca-82c44f299505}, stringData=null, type=kubernetes.io/dockerconfigjson}], kind=SecretList, metadata={resourceVersion=23566321, selfLink=/api/v1/namespaces/default/secrets, continue=null}}
java.lang.NullPointerException
	at com.skcc.cloudz.zcp.portal.management.namespace.service.NamespaceService.getSecrets(NamespaceService.java:356)
	at com.skcc.cloudz.zcp.portal.management.namespace.controller.NamespaceController.getSecrets(NamespaceController.java:213)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.servlet.resource.ResourceUrlEncodingFilter.doFilter(ResourceUrlEncodingFilter.java:59)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.oauth2.client.filter.OAuth2ClientContextFilter.doFilter(OAuth2ClientContextFilter.java:60)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.oauth2.client.filter.OAuth2ClientContextFilter.doFilter(OAuth2ClientContextFilter.java:60)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:108)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at io.micrometer.spring.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```
